import { DisplayData } from "./DisplayData";
import { PaymentTokensEntity } from "./PaymentTokensEntity";
import { PrimaryAssetContractsEntityOrAssetContract } from "./PrimaryAssetContractsEntityOrAssetContract";
import { Stats } from "./Stats";
import { Traits } from "./Traits";

export interface Collection {
  payment_tokens?: (PaymentTokensEntity)[] | null;
  primary_asset_contracts?: (PrimaryAssetContractsEntityOrAssetContract)[] | null;
  traits: Traits;
  stats: Stats;
  banner_image_url: string;
  chat_url?: null;
  created_date: string;
  default_to_fiat: boolean;
  description: string;
  dev_buyer_fee_basis_points: string;
  dev_seller_fee_basis_points: string;
  discord_url: string;
  display_data: DisplayData;
  external_url: string;
  featured: boolean;
  featured_image_url: string;
  hidden: boolean;
  safelist_request_status: string;
  image_url: string;
  is_subject_to_whitelist: boolean;
  large_image_url: string;
  medium_username?: null;
  name: string;
  only_proxied_transfers: boolean;
  opensea_buyer_fee_basis_points: string;
  opensea_seller_fee_basis_points: string;
  payout_address: string;
  require_email: boolean;
  short_description?: null;
  slug: string;
  telegram_url?: null;
  twitter_username: string;
  instagram_username?: null;
  wiki_url?: null;
  is_nsfw: boolean;
}
